local Components = script.Components

local VideKit = {}

VideKit.BillboardGui = require(Components.BillboardGui)

VideKit.CanvasGroup = require(Components.CanvasGroup)
VideKit.Frame = require(Components.Frame)

VideKit.AspectRatioConstraint = require(Components.AspectRatioConstraint)
VideKit.Corner = require(Components.Corner)
VideKit.FlexItem = require(Components.FlexItem)
VideKit.Padding = require(Components.Padding)

VideKit.ListLayout = require(Components.ListLayout)
VideKit.PageLayout = require(Components.PageLayout)

return VideKit
