local Components = script.Components

local VideKit = {}

VideKit.BillboardGui = require(Components.BillboardGui)
VideKit.ScreenGui = require(Components.ScreenGui)
VideKit.SurfaceGui = require(Components.SurfaceGui)

VideKit.CanvasGroup = require(Components.CanvasGroup)
VideKit.Frame = require(Components.Frame)
VideKit.ImageButton = require(Components.ImageButton)
VideKit.ImageLabel = require(Components.ImageLabel)
VideKit.ScrollingFrame = require(Components.ScrollingFrame)
VideKit.TextBox = require(Components.TextBox)

VideKit.AspectRatioConstraint = require(Components.AspectRatioConstraint)
VideKit.Corner = require(Components.Corner)
VideKit.FlexItem = require(Components.FlexItem)
VideKit.Gradient = require(Components.Gradient)
VideKit.Padding = require(Components.Padding)
VideKit.Scale = require(Components.Scale)
VideKit.SizeConstraint = require(Components.SizeConstraint)
VideKit.Stroke = require(Components.Stroke)

VideKit.GridLayout = require(Components.GridLayout)
VideKit.ListLayout = require(Components.ListLayout)
VideKit.PageLayout = require(Components.PageLayout)
VideKit.TableLayout = require(Components.TableLayout)

return VideKit
